-- =============================================
-- DANS OKULU YÖNETİM SİSTEMİ - VERİTABANI ŞEMASI
-- Database Schema for Dance School Management System
-- =============================================

-- 1. EĞİTMENLER TABLOSU
-- Instructors table: Stores information about dance instructors
create table instructors (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  specialty text, -- Örn: Salsa, Tango, Bachata
  phone text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. DERS TANIMLARI (Sınıflar)
-- Classes table: Defines specific class schedules (e.g., "Tuesday 19:00 Salsa")
create table classes (
  id bigint generated by default as identity primary key,
  name text not null, -- Örn: Başlangıç Seviye Salsa
  instructor_id bigint references instructors(id),
  day_of_week text, -- Pazartesi, Salı, Çarşamba, Perşembe, Cuma, Cumartesi, Pazar
  start_time time, -- 19:00, 20:30, vb.
  duration_minutes int default 60,
  price_monthly numeric, -- O sınıfın aylık ücreti (farklı olabilir)
  active boolean default true
);

-- 3. ÜYELER TABLOSU
-- Members table: Core member information and status tracking
create table members (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  phone text,
  join_date date default current_date,
  status text default 'active', -- active, frozen, archived
  notes text,
  last_payment_date date, -- Son ödeme yaptığı tarih
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. ÜYE - DERS EŞLEŞTİRMESİ (Çoka-Çok İlişki)
-- Member-Class relationship: Allows members to enroll in multiple classes
create table member_classes (
  member_id bigint references members(id),
  class_id bigint references classes(id),
  primary key (member_id, class_id)
);

-- 5. ÖDEMELER GEÇMİŞİ
-- Payments table: Financial transaction history
create table payments (
  id bigint generated by default as identity primary key,
  member_id bigint references members(id),
  amount numeric not null,
  payment_date date default current_date,
  payment_method text, -- Nakit, Kredi Kartı, Havale
  period_start date, -- Hangi dönem için? Örn: 10 Ekim
  period_end date,   -- 10 Kasım (28 gün sonrası)
  description text   -- "Elden alındı" vb. notlar
);

-- 6. DONDURULAN ÜYELİKLER (Log tutmak için)
-- Frozen memberships log: Tracks membership freeze periods
create table frozen_logs (
  id bigint generated by default as identity primary key,
  member_id bigint references members(id),
  start_date date not null,
  end_date date, -- Süresiz dondurmada boş olabilir (NULL)
  days_count int, -- Dondurma süresi (gün)
  reason text
);

-- =============================================
-- NOTLAR ve İŞ KURALLARI
-- =============================================

-- 1. ÖDEME DÖNGÜsÜ: 28 günlük (4 haftalık) dönemler halinde takip edilir.
--    Örn: 1 Kasım'da ödeme yapan üyenin bir sonraki ödemesi 29 Kasım'dır.

-- 2. SOFT DELETE: Hiçbir kayıt gerçekten silinmez.
--    'status' alanı 'archived' yapılarak görünmezlik sağlanır.

-- 3. ÇOKLU DERS: Bir üye birden fazla derse katılabilir.
--    member_classes tablosu üzerinden many-to-many ilişki kurulur.

-- 4. DONDURMA: Üye dondurulduğunda frozen_logs tablosuna kayıt atılır
--    ve next_payment_due_date donma süresi kadar ötelenir.
