-- Create frozen_logs table if it doesn't exist
CREATE TABLE IF NOT EXISTS frozen_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE NOT NULL,
  member_class_id BIGINT REFERENCES member_classes(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE,
  reason TEXT,
  days_count INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_frozen_logs_member_id ON frozen_logs(member_id);
CREATE INDEX IF NOT EXISTS idx_frozen_logs_member_class_id ON frozen_logs(member_class_id);
CREATE INDEX IF NOT EXISTS idx_frozen_logs_active ON frozen_logs(member_id, end_date) WHERE end_date IS NULL;

-- Enable RLS
ALTER TABLE frozen_logs ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations (adjust based on your auth requirements)
CREATE POLICY "Enable all access for frozen_logs" ON frozen_logs
  FOR ALL
  USING (true)
  WITH CHECK (true);
