-- 1. Dondurma tablosunu 'Süresiz' dondurmaya uygun hale getir
ALTER TABLE frozen_logs ALTER COLUMN end_date DROP NOT NULL;
ALTER TABLE frozen_logs ADD COLUMN IF NOT EXISTS days_count INTEGER;

-- 2. Dans Türlerini Tanımla (Salsa, Zeybek vb.)
CREATE TABLE dance_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE
);

-- 3. Sınıfları Dans Türüne Bağla
ALTER TABLE classes ADD COLUMN dance_type_id BIGINT REFERENCES dance_types(id);

-- 4. Eğitmenler için Varsayılan Komisyon Oranı Ekle
ALTER TABLE instructors ADD COLUMN default_commission_rate NUMERIC DEFAULT 30;

-- 5. Eğitmen Komisyon Matrisi (Hoca + Ders Tipi = Özel Oran)
CREATE TABLE instructor_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instructor_id BIGINT REFERENCES instructors(id) NOT NULL,
  dance_type_id BIGINT REFERENCES dance_types(id) NOT NULL,
  rate NUMERIC NOT NULL, -- Örn: 60
  UNIQUE(instructor_id, dance_type_id)
);

-- 6. Eğitmen Hakediş Defteri (Gelecek vadeli ödemeler için)
CREATE TABLE instructor_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instructor_id BIGINT REFERENCES instructors(id),
  student_payment_id BIGINT REFERENCES payments(id),
  amount NUMERIC NOT NULL,
  due_date DATE NOT NULL, -- Hakediş tarihi
  status TEXT DEFAULT 'pending', -- pending, payable, paid, cancelled
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. Eğitmenlere Yapılan Fiili Ödemeler
CREATE TABLE instructor_payouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instructor_id BIGINT REFERENCES instructors(id),
  amount NUMERIC NOT NULL,
  payment_date DATE DEFAULT current_date,
  note TEXT
);
